services:
  postgres:
    image: pgvector/pgvector:pg18
    container_name: postgres-pgvector
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: privait_dev
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/18/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
  # postgres:
  #   image: postgres:17
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: app_dev
  #   volumes:
  #     - postgres:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  redis:
    image: redis:7.4.1
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  elasticmq:
    image: softwaremill/elasticmq-native:latest
    ports:
      - 9324:9324
      - 9325:9325
    volumes:
      - ./docker/elasticmq.conf:/opt/elasticmq.conf
      - elasticmq:/data
  mailpit:
    image: axllent/mailpit:latest
    volumes:
      - mailpit:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
  rustfs:
    image: rustfs/rustfs:latest
    ports:
      - '8080:8080'
      - '9001:9001'
    volumes:
      - rustfs:/data
    # Using default RUSTFS_ACCESS_KEY or RUSTFS_SECRET_KEY. Override them in production
    environment:
      RUSTFS_ACCESS_KEY: access
      RUSTFS_SECRET_KEY: secret
      RUSTFS_DATA_DIR: /data

volumes:
  postgres:
  elasticmq:
  mailpit:
  redis:
  rustfs:
